# 网页信息
title: MiKit
author: chzng
email: chzng@outlook.com
description: Jekyll theme mikit

# 自定义URL
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chzng.github.io" # the base hostname & protocol for your site

# 社交链接
github_username: mi-kit
rss: rss


# 显示摘要
show_excerpts: false # set to true to show excerpts on the homepage

# 链接 permalink
permalink: /:title/

# 限制日志数量
limit_posts: 0

# 相关日志
lsi: true

# 语法高亮
highlighter: pygments

# Markdown渲染器
markdown: maruku

# 分页 paginate
paginate: 3
paginate_path: "page:num"

# 时区 Time Zone
timezone: America/New_York

# 日期格式化
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in order as they should show up
# header_pages:
# - about.html

# Build settings
theme: minima


# 插件
Safe: false

plugins:
 - jekyll-feed
 - jekyll-seo-tag


